# Generated by Django 6.0.6 on 2026-06-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
